const CONFIG = {
    titleWeb: "For my babiboo <3",
    introTitle: 'Anh Hoàng iu dấu :*',
    introDesc: `Đây là bức thư tình đáng iu mà tiểu tiên nữ Trần Quỳnh Trang gửi đến anh`,
    btnIntro: 'Hun vợ 💋',
    title: 'Yêu anh, yêu những giấc mơ 🥰',
    desc: 'Giấc mơ dài thật dài và em không có lối raa ',
    btnYes: 'Anh cũng rất nhớ em 🥺',
    btnNo: 'Anh nhớ em :3',
    question: 'Trên thế giới hơn 7 tỉ nụ cười nhưng đối với em nụ cười của anh mới là đẹp nhất <3',
    btnReply: 'Gửi cho anh iu <3',
    reply: 'Anh nhớ ăn uống đầy đủ đừng để đau dạ dày nhé <33333333',
    mess: 'Anh biết mà 🥰. Anh chắc chắn sẽ làm thế 😘😘',
    messDesc: 'Vậy anh cũng chú ý đi đứng cẩn thận đừng có ngã vào tim em nào nhee',
    btnAccept: 'Chỉ ở trong tim em được thuii',
    messLink: 'https://www.rd.com/wp-content/uploads/2020/12/LoveMeme6.jpg' 
